name: Compare functions
on: [push, workflow_dispatch]
jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - run: printenv
              env:
                CONTAINS_FUNC: ${{ contains('Hello, world', 'Hello') }}
                STARTS_WITH_FUNC: ${{ startsWith('Hello, world', 'Hello') }}
                ENDS_WITH_FUNC: ${{ endsWith('Hello, world', 'world') }}